config/routes.rb
Rails.application.routes.draw do

  post "/courses/:id/book", to: "courses#book", as: :book_course

  get "/enrollments/mine_booked", to: "enrollments#mine_booked", as: :mine_booked

  resources :teachers

  resources :students

  resources :enrollments

  resources :bookings

  resources :campuses

  resources :coursetypes

  resources :classrooms

  resources :courses do
      collection do
        get :past, to: 'courses#past_courses'
        get :current, to: 'courses#current_courses'
        get :future, to: 'courses#future_courses'
      end
    end

  devise_for :users

  resources :users, only: [:index, :show] do
    member do
      post "make_teacher", to: "users#make_teacher"
      post "make_not_teacher", to: "users#make_not_teacher"
    end
  end
  
  get "/my_profile", to: "users#show", as: :my_profile

  devise_scope :user do
    authenticated :user do
      root to: "courses#index", as: :authenticated_root
    end

    unauthenticated do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  
end

app/controllers/coursetypes_controller.rb
class CoursetypesController < ApplicationController
  before_action :set_coursetype, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @coursetypes = Coursetype.all
    respond_with(@coursetypes)
  end

  def show
    respond_with(@coursetype)
  end

  def new
    @coursetype = Coursetype.new
    respond_with(@coursetype)
  end

  def edit
  end

  def create
    @coursetype = Coursetype.new(coursetype_params)
    @coursetype.save
    respond_with(@coursetype)
  end

  def update
    @coursetype.update(coursetype_params)
    respond_with(@coursetype)
  end

  def destroy
    @coursetype.destroy
    respond_with(@coursetype)
  end

  private
    def set_coursetype
      @coursetype = Coursetype.find(params[:id])
    end

    def coursetype_params
      params.require(:coursetype).permit(:name, :description, :icon, :intensity, :remote_icon_url)
    end
end

app/helpers/coursetypes_helper.rb
module CoursetypesHelper
end

app/views/coursetypes/_form.html.erb
<%= form_for(@coursetype) do |f| %>
  <% if @coursetype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coursetype.errors.count, "error") %> prohibited this coursetype from being saved:</h2>

      <ul>
      <% @coursetype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :intensity %><br>
    <%= f.text_field :intensity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coursetypes/edit.html.erb
<h1>Editing coursetype</h1>

<%= render 'form' %>

<%= link_to 'Show', @coursetype %> |
<%= link_to 'Back', coursetypes_path %>

app/views/coursetypes/index.html.erb
<h1>Listing coursetypes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Icon</th>
      <th>Intensity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coursetypes.each do |coursetype| %>
      <tr>
        <td><%= coursetype.name %></td>
        <td><%= coursetype.description %></td>
        <td><%= coursetype.icon %></td>
        <td><%= coursetype.intensity %></td>
        <td><%= link_to 'Show', coursetype %></td>
        <td><%= link_to 'Edit', edit_coursetype_path(coursetype) %></td>
        <td><%= link_to 'Destroy', coursetype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coursetype', new_coursetype_path %>

app/views/coursetypes/new.html.erb
<h1>New coursetype</h1>

<%= render 'form' %>

<%= link_to 'Back', coursetypes_path %>

app/views/coursetypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coursetype.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @coursetype.description %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @coursetype.icon %>
</p>

<p>
  <strong>Intensity:</strong>
  <%= @coursetype.intensity %>
</p>

<%= link_to 'Edit', edit_coursetype_path(@coursetype) %> |
<%= link_to 'Back', coursetypes_path %>