config/routes.rb
Rails.application.routes.draw do

  post "/courses/:id/book", to: "courses#book", as: :book_course

  get "/enrollments/mine_booked", to: "enrollments#mine_booked", as: :mine_booked

  resources :teachers

  resources :students

  resources :enrollments

  resources :bookings

  resources :campuses

  resources :coursetypes

  resources :classrooms

  resources :courses do
      collection do
        get :past, to: 'courses#past_courses'
        get :current, to: 'courses#current_courses'
        get :future, to: 'courses#future_courses'
      end
    end

  devise_for :users

  resources :users, only: [:index, :show] do
    member do
      post "make_teacher", to: "users#make_teacher"
      post "make_not_teacher", to: "users#make_not_teacher"
    end
  end
  
  get "/my_profile", to: "users#show", as: :my_profile

  devise_scope :user do
    authenticated :user do
      root to: "courses#index", as: :authenticated_root
    end

    unauthenticated do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :user
  belongs_to :course

#scoped associations

  has_many :teachers, -> { where {courserole :teacher} }, source: :user
  has_many :tas, -> { where {courserole :ta} },  source: :user
  has_many :students, -> { where {courserole :student} }, source: :user

  validates :user_id, uniqueness: {scope: :course, message: " is already booked on this course"}, :on => [ :create, :update ]

  # validate :teacher_not_already_booked, :on => [ :create, :update ]
#trying to add a validation for case if teacher is already booked as student. 

  def fullname
        "#{prename} #{lastname}"
  end


  #trying to add a validation for case if teacher is already booked as student. 
  # private
  # def teacher_not_already_booked
  #   errors.add :user_id, "this teacher is already booked as a student on that course" if user_id == teacher_ids
  # end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @enrollments = Enrollment.all
    respond_with(@enrollments)
  end

  def show
    respond_with(@enrollment)
  end

  def new
    @enrollment = Enrollment.new
    respond_with(@enrollment)
  end

  def edit
  end

  def create
    @enrollment = Enrollment.new(enrollment_params)
    @enrollment.save
    respond_with(@enrollment)
  end

  def update
    @enrollment.update(enrollment_params)
    respond_with(@enrollment)
  end

  def destroy
    @enrollment.destroy
    respond_with(@enrollment)
  end

  def mine_booked
    @enrollments = Enrollment.where(user_id: current_user.id, courserole: :student)
    if @enrollments.empty?
      redirect_to  :back, notice: "You haven't booked a course with GA yet. Book one now!".html_safe
    else
      respond_with(@enrollments)
    end
  end
  

  private
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    def enrollment_params
      params.require(:enrollment).permit(:user_id, :course_id, :courserole)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_for(@enrollment) do |f| %>
  <% if @enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.text_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :courserole %><br>
    <%= f.text_field :courserole %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render 'form' %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<h1>Listing enrollments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Course</th>
      <th>Courserole</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.user %></td>
        <td><%= enrollment.course %></td>
        <td><%= enrollment.courserole %></td>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/mine_booked.html.erb
<h1>Courses I have booked:</h1>
<br>
<% @enrollments.collect do |enrollment| %> 
<div class="allusers">

<h1><strong><%= enrollment.course.try :name %></strong></h1>

<h3>Course-Start: </h3>
<p><%= enrollment.course.start_date %></p>

<h3>Course-End: </h3>
<p><%= enrollment.course.end_date %></p>

<br>
<%= link_to 'Cancel my enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-large btn-primary' if can? :destroy, Enrollment %>




    </div>
  <br>
  <br>



  <% end %>

<br>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render 'form' %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @enrollment.user %>
</p>

<p>
  <strong>Course:</strong>
  <%= @enrollment.course %>
</p>

<p>
  <strong>Courserole:</strong>
  <%= @enrollment.courserole %>
</p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>