config/routes.rb
Rails.application.routes.draw do

  post "/courses/:id/book", to: "courses#book", as: :book_course

  get "/enrollments/mine_booked", to: "enrollments#mine_booked", as: :mine_booked

  resources :teachers

  resources :students

  resources :enrollments

  resources :bookings

  resources :campuses

  resources :coursetypes

  resources :classrooms

  resources :courses do
      collection do
        get :past, to: 'courses#past_courses'
        get :current, to: 'courses#current_courses'
        get :future, to: 'courses#future_courses'
      end
    end

  devise_for :users

  resources :users, only: [:index, :show] do
    member do
      post "make_teacher", to: "users#make_teacher"
      post "make_not_teacher", to: "users#make_not_teacher"
    end
  end
  
  get "/my_profile", to: "users#show", as: :my_profile

  devise_scope :user do
    authenticated :user do
      root to: "courses#index", as: :authenticated_root
    end

    unauthenticated do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  
end

app/models/course.rb
class Course < ActiveRecord::Base

  has_many :enrollments
  has_many :users, through: :enrollments

  has_many :bookings
  has_many :classrooms, through: :bookings

  belongs_to :coursetype


  validates :name, presence: true

  validates :start_date, date: { before: :end_date , message: 'of the course can\'t be before the end date!' }

  validates :start_date, date: { after_or_equal_to: Date.today, message: 'can\'t be in the past' }, on: :create
  
  validates :teacher_id, presence: true

  validate :immersive_course

  validate :workshop_course
            

  has_many :teachers, -> { where(enrollments: {courserole: :teacher}) }, through: :enrollments, source: :user
  #this gives a teacher_ids, a collection of all the ids for the teachers. 

  has_many :tas, -> { where(enrollments: {courserole: :ta}) }, through: :enrollments, source: :user
  has_many :students, -> { where(enrollments: {courserole: :student}) }, through: :enrollments, source: :user

  scope :past_courses, ->  { where("end_date < ?", Date.today) }

  scope :current_courses, -> { where(" ? BETWEEN start_date AND end_date", Date.today) }

  scope :future_courses, -> { where(" ? < start_date", Date.today) }

 

  def teacher_id
    teachers.first.try :id
  end


  #this is the setter for the teacher. we hat to create a new one because rails doesnt give it to us. 
  def teacher_id=(value)
    self.teacher_ids = [value]
    value
  end
  #if coursetype intensity is equal to immersive the end date has to be at least 12 weeks after the start date. 

 

  private
  def immersive_course
    if coursetype.intensity
    errors.add :coursetype_id, "\'Immersive Course\' has to be at least 12 weeks long" if coursetype.intensity == "Immersive" && start_date + 12.week > end_date 
  end
  end

  def workshop_course
    if coursetype.intensity
    errors.add :coursetype_id, "\'Workshops\' can't be longer than two days" if coursetype.intensity == "Workshop" && start_date + 2.day < end_date 
    end
  end


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
before_action :set_course, only: [:show, :edit, :update, :destroy, :book_course]

before_action :set_teachers, only: [:new, :edit, :update, :create]

before_action :set_tas, only: [:new, :edit, :update, :create]


  respond_to :html

  def index
    # @courses = Course.all
    # respond_with(@courses)

    @q = Course.search(params[:q])
    @courses = @q.result(distinct: true)
  end

  def show
    respond_with(@course)
  end

  def new
    @course = Course.new
    respond_with(@course)
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    @course.save
    respond_with(@course)
  end

  def update
    @course.update(course_params)
    respond_with(@course)
  end

  def destroy
    @course.destroy
    respond_with(@course)
  end


  def book
    @enrollment = @course.enrollments.new(user_id: current_user.id, courserole: :student)

    if @enrollment.save
      redirect_to @course, notice: "Your course is booked. We're looking forward to see you at GA!".html_safe
    else
      render :show
    end
  end


  def past_courses
    index
    @courses = Course.past_courses
    render :index
  end

  def current_courses
    index
    @courses = Course.current_courses
    render :index
  end

  def future_courses
    index
    @courses = Course.future_courses
    render :index
  end

 

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def set_teachers
      @teachers = User.where(canbeteacher: true)
    end

    def set_tas
      @tas = User.where(canbeteacher: true)
    end

  #in the collection select it shows only these users. 


    def course_params
      params.require(:course).permit(:name, :start_date, :end_date, :coursetype_id, :teacher_id, :classroom_ids => [], :ta_ids => [])
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
<% if @course.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

  <ul>
    <% @course.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<br>
<div class="field">
  <%= f.label :start_date %><br>
  <%= f.date_select :start_date, :order => [:day, :month, :year]%>
</div>
<br>
<div class="field">
  <%= f.label :end_date %><br>
  <%= f.date_select :end_date, :order => [:day, :month, :year] %>
</div>
<br>

<div class="field">
  <%= f.label :coursetype_id %><br>

  <%= f.collection_select(:coursetype_id, (Coursetype.order :name).distinct,:id,:name, prompt: :true)%>
</div>
<br>

<!-- set up boolean to make that working (@teachers) -->
<div class="field">
  <%= f.label :teacher_id %><br>
  <%= f.collection_select(:teacher_id, @teachers, :id, :fullname, prompt: :true)%>
</div>
<br>

<div class="field">
  <%= f.label "Teacher-Assistants: "%><br>
 <%= f.collection_check_boxes(:ta_ids, @tas, :id, :fullname) do |b| -%>

  <%= b.check_box %>
  <%= b.label %>
  <br>
  <%end%>


  
  <div class="field">

    <br>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course, :class => 'btn btn-large btn-primary'%> 
<%= link_to 'Back', courses_path, :class => 'btn btn-large btn-primary' %>

app/views/courses/index.html.erb
<h1>Filter Courses:</h1>
<br>


<%= search_form_for @q do |c| %>


  <%=c.label :coursetype_id %>

  <%= c.collection_select(:coursetype_intensity_eq, (Coursetype.select :intensity).uniq, :intensity , :intensity) %>

  <%= c.submit%>

<% end %>

<!-- creating radio check boxes for filter functions courses in the past/current/future? -->



<h1>GA courses:</h1>
<br>

<% @courses.each do |course| %>
<div class="allusers">

  <h1><strong><%= course.name %></strong></h1>

  <p><%= course.coursetype.try :name %></p>

  <h3>Course-Start: </h3>
  <p><%= course.start_date %></p>

  <h3>Course-End: </h3>
  <p><%= course.end_date %></p>



  <%= link_to 'Show this course', course, :class => 'btn btn-large btn-primary' %>
  <%= link_to 'Edit this course', edit_course_path(course), :class => 'btn btn-large btn-primary' if can? :edit, Course %>
  <%= link_to 'Delete this course', course, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-large btn-primary' if can? :destroy, Course %>
</div>
<br>
<br>

<% end %>

<br>

app/views/courses/new.html.erb
<h1>Let's create a new GA course </h1>
<br>

<%= render 'form' %>

<%= link_to 'Back', courses_path, :class => 'btn btn-large btn-primary' %>

app/views/courses/show.html.erb
<% if @enrollment && @enrollment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

    <ul>
    <% @enrollment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>




<%= image_tag(@course.coursetype.try(:icon), :class => "coursetype_img")%>



  <h2><%= @course.name %></h2>


<p>
  <strong>Coursetype:</strong>
  <%= @course.coursetype.try :name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @course.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @course.end_date %>
</p>



<p>
  <strong>Description:</strong>
  <%= @course.coursetype.try :description %>
</p>



<p>
  <strong>Teacher:</strong>
  <% @course.teachers.each do |teacher|%> 
  <li><%=teacher.fullname%></li>
    <% end%>
  </p>

  <p>
    <strong>Teacher-Assistants:</strong>
    <% @course.tas.each do |ta|%> 
    <li><%= ta.fullname %></li>
    <% end%>
  </p>

  <p>
    <strong>Students:</strong>
    <% @course.students.each do |student|%> 
    <li><%=  student.fullname %></li>
    <% end%>
  </p>

  

 <td><%= link_to 'Book this course', book_course_path(@course), method: :post, data: { confirm: 'Are you sure you want to book this course?' }, :class => 'btn btn-large btn-primary' if can? :book, Course %></td>

  <%= link_to 'Edit', edit_course_path(@course), :class => 'btn btn-large btn-primary' if can? :edit, Course%>
  <%= link_to 'Back', courses_path, :class => 'btn btn-large btn-primary' %>