config/routes.rb
Rails.application.routes.draw do

  post "/courses/:id/book", to: "courses#book", as: :book_course

  get "/enrollments/mine_booked", to: "enrollments#mine_booked", as: :mine_booked

  resources :teachers

  resources :students

  resources :enrollments

  resources :bookings

  resources :campuses

  resources :coursetypes

  resources :classrooms

  resources :courses do
      collection do
        get :past, to: 'courses#past_courses'
        get :current, to: 'courses#current_courses'
        get :future, to: 'courses#future_courses'
      end
    end

  devise_for :users

  resources :users, only: [:index, :show] do
    member do
      post "make_teacher", to: "users#make_teacher"
      post "make_not_teacher", to: "users#make_not_teacher"
    end
  end
  
  get "/my_profile", to: "users#show", as: :my_profile

  devise_scope :user do
    authenticated :user do
      root to: "courses#index", as: :authenticated_root
    end

    unauthenticated do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  
end

app/views/layouts/_menu.html.erb
<%= nav_bar :fixed => :top, :responsive => true do %>
    <div class="title">
    <%= menu_group :pull => :left do %>
    <%= menu_item "GENERAL ASSEMBLY"%>

    <% end %>
    </div>


    <%= menu_group :pull => :right do %>
        <% if current_user %>
        <%= menu_item "Log Out", destroy_user_session_path, method: :delete %>
        <% else %>
        <% end %>
    <% end %>

    <%= menu_group do %>

    <%= menu_divider %>
        <% if can? :read, Course%>
        <%= drop_down  "Courses" do %>
        <%= menu_item("All Courses", courses_path) if can? :read, Course %>
        -        <%= menu_item "Create new course", new_course_path if can? :create, Course %>
        -        <%= menu_item "My Courses", mine_booked_path if can? :read, Course %>
        <% end   %>
        <% end   %>


    <%= menu_item "All Teachers", teachers_path if can? :read, :teacher %>
    <%= menu_item "All Users", users_path if can? :read, User %>
    <%= menu_item "Classrooms", classrooms_path if can? :read, Classroom %>
    <%= menu_item "My Profile",  my_profile_path if current_user %>

    <% end %>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GaScheduleApp</title>
  <link href='http://fonts.googleapis.com/css?family=News+Cycle:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%=image_tag "ga.png", class: "brand", :data =>  {"20" => "transform[bounce]:rotate(0deg); left: 10px; top: 50px", "2000" => "transform[bounce]:rotate(360deg); left: 10px; top: 35px"} %>


  <div class='login'>
    <% if current_user %>
    <%= current_user.email %>
    <%#= link_to "Log out", destroy_user_session_path, method: :delete %>
    <% else %>
    <%#= link_to "Sign In", new_user_session_path %>
    <%#= link_to "Register", new_user_registration_path %>
    <% end %>
  </div>

  
  <%= render partial: "/layouts/menu"%>

  <div class="signup">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

  <div class="container-fluid">
   <div class="row">
    <div class="col-xs-6 col-xs-offset-3">

      <%= yield %>
    </div>
  </div>
</div>


<footer class="footer navbar-fixed-bottom">
 <p>If you have any questions or suggestions to improve our App, please contact us on <%= mail_to "help@ga.co.uk" %></p>
 <p>© 2014 General Assembly. All rights reserved.</p>
</footer>




</body>
</html>